# Generated by Django 4.2.15 on 2024-09-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SttArtApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='wavFile',
        ),
        migrations.AddField(
            model_name='recording',
            name='wavFilePath',
            field=models.FileField(default='default.wav', upload_to='recordings/'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
