# Generated by Django 4.2.15 on 2024-09-02 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SttArtApp', '0002_remove_recording_wavfile_recording_wavfilepath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='recording_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
